import type { AdvancedSelectProps, AlertPopupProps, AlertProps, BadgeProps, ButtonGroupProps, ButtonProps, CheckboxProps, CardProps, CardBodyProps, CardFooterProps, CardHeaderProps, CollapsableCheckboxProps, CollapsablePanelProps, CollapsableRadioProps, CollapsableToggleProps, CollapseProps, DrawerProps, DropdownButtonProps, DropdownItemProps, DropdownMenuProps, DropdownProps, FloatingPanelProps, IconComponentProps, LabelProps, LinkProps, LoadingProps, MessageProps, MobilePanelProps, ModalProps, MultiRangeSliderProps, MultiSelectProps, NavbarProps, NavItemProps, NavLinkProps, NavMenuProps, NavProps, NumericInputProps, PageNumberProps, PaginationProps, PaperProps, PopperProps, ProgressProps, RadioProps, ResizableProps, ScrollListProps, SelectOptionProps, SelectProps, SliderProps, SurfaceProps, SVGProps, SwitchProps, TabProps, TabsProps, TextAreaProps, TextInputProps, TooltipProps, ImageProps, NotificationProps } from 'jimu-ui';
import type { ComponentNameToPartKey } from './parts';
type ComponentsStyleStateMapping = {
    [x in keyof ComponentNameToPartKey]: any;
};
export interface ComponentsStyleStateList extends ComponentsStyleStateMapping {
    AdvancedSelect: AdvancedSelectProps;
    Alert: AlertProps;
    AlertPopup: AlertPopupProps;
    Badge: BadgeProps;
    Button: ButtonProps;
    ButtonGroup: ButtonGroupProps;
    Card: CardProps;
    CardHeader: CardHeaderProps;
    CardBody: CardBodyProps;
    CardFooter: CardFooterProps;
    Checkbox: CheckboxProps;
    Collapse: CollapseProps;
    CollapsablePanel: CollapsablePanelProps;
    CollapsableCheckbox: CollapsableCheckboxProps;
    CollapsableRadio: CollapsableRadioProps;
    CollapsableToggle: CollapsableToggleProps;
    Drawer: DrawerProps;
    Dropdown: DropdownProps;
    DropdownMenu: DropdownMenuProps;
    DropdownItem: DropdownItemProps;
    DropdownButton: DropdownButtonProps;
    FloatingPanel: FloatingPanelProps;
    Icon: IconComponentProps;
    Image: ImageProps;
    Label: LabelProps;
    Link: LinkProps;
    Loading: LoadingProps;
    Message: MessageProps;
    MobilePanel: MobilePanelProps;
    Modal: ModalProps;
    MultiRangeSlider: MultiRangeSliderProps;
    MultiSelect: MultiSelectProps;
    Nav: NavProps;
    Navbar: NavbarProps;
    NavItem: NavItemProps;
    NavLink: NavLinkProps;
    NavMenu: NavMenuProps;
    Notification: NotificationProps;
    NumericInput: NumericInputProps;
    Option: SelectOptionProps;
    Pagination: PaginationProps;
    PageNumber: PageNumberProps;
    Paper: PaperProps;
    Progress: ProgressProps;
    Popper: PopperProps;
    Radio: RadioProps;
    Resizable: ResizableProps;
    Scrollable: ResizableProps;
    ScrollList: ScrollListProps;
    Select: SelectProps;
    Slider: SliderProps;
    Surface: SurfaceProps;
    SVG: SVGProps;
    Switch: SwitchProps;
    Tab: TabProps;
    Tabs: TabsProps;
    TextArea: TextAreaProps;
    TextInput: TextInputProps;
    Tooltip: TooltipProps;
}
export {};
