module.exports = [
  '__mocks__/',
  'builder/',
  'dist/',
  'jimu-arcgis/',
  'jimu-core/',
  'jimu-data-source/',
  'jimu-for-builder/',
  'jimu-for-test/',
  'jimu-icons/',
  'jimu-layouts/',
  'jimu-theme/',
  'jimu-ui/',
  'scripts/',
  'types/',
  'webpack/',

  'node_modules/',
  'webpack*.js',
  'gulpfile.js',
  'jest.config.js',
  'jest-systemjs-transformer.js',
  'eslint-ignore.js',
  'eslint-config.js',
  'npm-bootstrap-extensions.js',

  '**/*.md',
  '**/*.mdx',
  '**/*.html',
  '**/*.json',
  '**/*.d.ts',
]