import { type DataSourceManager, type DataSource } from 'jimu-core';
import type { Constructor } from '../types';
export declare const SetDataSourceMixinImpl: <TBase extends Constructor<DataSource>>(Base: TBase) => (abstract new (...args: any[]) => {
    id: string;
    dataSourceManager: DataSourceManager;
    childDataSourcesCreated: boolean;
    childDataSourcePromises: {
        [childDsId: string]: Promise<DataSource>;
    };
    /**
     * Get all child data sources' child id.
     * The child id is generated from original data (AGOL/portal item or a remote database).
     * The child id can be the JS API layer ID or layer service ID, without spaces.
     */
    getChildIds(): string[];
    /**
     * Create a child data source by its ID.
     * @param childDsId the data source id, used in data source constructor options.
     * @param jimuChildId the jimu child id, used in data source constructor options.
     * @param childId the short ID for child data source, generated by implement classes, see `getChildIds` method.
     */
    createChildDataSourceById(childDsId: string, jimuChildId: string, childId: string): Promise<DataSource>;
    childDataSourcesReady(): Promise<DataSource[]>;
    updateAreChildDataSourcesCreated(): void;
    areChildDataSourcesCreated(): boolean;
    setChildDataSourcesCreated(created: boolean): void;
    createChildDataSourcesRecursively(): Promise<DataSource[]>;
    createChildDataSources(): Promise<DataSource[]>;
    createDataSourceById(dataSourceId: string): Promise<DataSource>;
    findChildDataSourceIdByDescendantDataSourceId(dataSourceId: string): string;
    getChildDataSourceIds(): string[];
    destroy(): void;
    areSomeChildDataSourcesPending(): Promise<boolean>;
    getChildDataSourceId(jimuChildId: string): string;
    getChildDataSources(): DataSource[];
    getAllChildDataSources(): DataSource[];
    getChildDataSource(jimuChildId: string): DataSource;
    getJimuChildId(childId: string): string[];
    clearChildDataSourcePromise(childDsId: string): void;
}) & TBase;
