import Quill from 'quill';
import type Editor from 'quill/quill';
import type BlockBlot from 'quill/blots/block';
import type EmbedBlot from 'quill/blots/embed';
import type InlineBlot from 'quill/blots/inline';
import type TextBlot from 'quill/blots/text';
import type ClipboardStatic from 'quill/modules/clipboard';
import type KeyboardStatic from 'quill/modules/keyboard';
import type { Attributor, BlotConstructor } from 'parchment';
import type { Delta as DeltaValue, EmitterSource, Op as Operation, Range as RichSelection } from 'quill/core';
declare const Parchment: typeof import("parchment");
declare const Delta: typeof DeltaValue;
declare const Embed: typeof EmbedBlot;
declare const Inline: typeof InlineBlot;
declare const Block: typeof BlockBlot;
declare const Break: typeof EmbedBlot;
declare const Cursor: typeof EmbedBlot;
declare const Text: typeof TextBlot;
declare const HeaderFormat: BlotConstructor;
declare const AlignFormat: Attributor;
declare const DirectionFormat: Attributor;
declare const FontFormat: Attributor;
declare const FontSizeFormat: Attributor;
export { Quill, Parchment, Delta, Embed, Inline, Block, Break, Cursor, Text, AlignFormat, DirectionFormat, FontFormat, FontSizeFormat, HeaderFormat };
export type EventType = 'editor-change' | 'text-change' | 'selection-change';
export type { Editor, DeltaValue, Operation, RichSelection, EmitterSource, ClipboardStatic, KeyboardStatic, BlockBlot, EmbedBlot, InlineBlot, TextBlot };
